#!/bin/zsh

# TREC DL 2019 No PRF Retrieval
python3 main.py --result_output ./result/trec_deep_2019/ANCE_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
python3 main.py --result_output ./result/trec_deep_2019/RepBERT_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

# TREC DL 2020 No PRF Retrieval
python3 main.py --result_output ./result/trec_deep_2020/ANCE_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
python3 main.py --result_output ./result/trec_deep_2020/RepBERT_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

# WebAP No PRF Retrieval
python3 main.py --result_output ./result/webap/ANCE_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json
python3 main.py --result_output ./result/webap/RepBERT_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json

# WikiPassageQA No PRF Retrieval
python3 main.py --result_output ./result/wikipassageqa/ANCE_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json
python3 main.py --result_output ./result/wikipassageqa/RepBERT_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json

# TREC CAsT 2019 No PRF Retrieval
python3 main.py --result_output ./result/trec_cast/2019/ANCE_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json
python3 main.py --result_output ./result/trec_cast/2019/RepBERT_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json

# DL HARD No PRF Retrieval
python3 main.py --result_output ./result/dl_hard/ANCE_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
python3 main.py --result_output ./result/dl_hard/RepBERT_PRF_Runs/no_prf_retrieval.res --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

for prf in 1 3 5 10
do
  # TREC DL 2019 AVG PRF
  python3 main.py --result_output ./result/trec_deep_2019/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2019/ANCE_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
  python3 main.py --result_output ./result/trec_deep_2019/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2019/RepBERT_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

  # TREC DL 2020 AVG PRF
  python3 main.py --result_output ./result/trec_deep_2020/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2020/ANCE_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
  python3 main.py --result_output ./result/trec_deep_2020/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2020/RepBERT_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

  # WebAP AVG PRF
  python3 main.py --result_output ./result/webap/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/webap/ANCE_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json
  python3 main.py --result_output ./result/webap/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/webap/RepBERT_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json

  # WikiPassageQA AVG PRF
  python3 main.py --result_output ./result/wikipassageqa/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/wikipassageqa/ANCE_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json
  python3 main.py --result_output ./result/wikipassageqa/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/wikipassageqa/RepBERT_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json

  # TREC CAsT 2019 AVG PRF
  python3 main.py --result_output ./result/trec_cast/2019/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_cast/2019/ANCE_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json
  python3 main.py --result_output ./result/trec_cast/2019/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_cast/2019/RepBERT_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json

  # DL HARD AVG PRF
  python3 main.py --result_output ./result/dl_hard/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/dl_hard/ANCE_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
  python3 main.py --result_output ./result/dl_hard/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/dl_hard/RepBERT_PRF_Runs/prf_retrieval.res --prf_method avg --iterations 1 --prf "${prf}" --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

  for i in 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
  do
    # TREC DL 2019 Rocchio PRF
    python3 main.py --result_output ./result/trec_deep_2019/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2019/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/trec_deep_2019/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2019/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/trec_deep_2019/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2019/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/trec_deep_2019/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2019/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2019/query/msmarco-2019test-queries.tsv --qrels_path ./data/trec_deep_2019/qrels/full.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

    # TREC DL 2020 Rocchio PRF
    python3 main.py --result_output ./result/trec_deep_2020/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2020/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/trec_deep_2020/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2020/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/trec_deep_2020/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2020/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/trec_deep_2020/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_deep_2020/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_deep_2020/query/msmarco-test2020-queries.tsv --qrels_path ./data/trec_deep_2020/qrels/2020-qrels-pass-no1_other.txt --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

    # WebAP Rocchio PRF
    python3 main.py --result_output ./result/webap/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/webap/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json
    python3 main.py --result_output ./result/webap/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/webap/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json
    python3 main.py --result_output ./result/webap/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/webap/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json
    python3 main.py --result_output ./result/webap/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/webap/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/webap/query/full_queries.tsv --qrels_path ./data/webap/qrels/full.qrels --collection_index ./data/webap/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/webap/collection/mapped_collection.tsv --mapper_path ./data/webap/index/PID_Mapping.json

    # WikiPassageQA Rocchio PRF
    python3 main.py --result_output ./result/wikipassageqa/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/wikipassageqa/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json
    python3 main.py --result_output ./result/wikipassageqa/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/wikipassageqa/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json
    python3 main.py --result_output ./result/wikipassageqa/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/wikipassageqa/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json
    python3 main.py --result_output ./result/wikipassageqa/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/wikipassageqa/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/wikipassageqa/query/full_queries.tsv --qrels_path ./data/wikipassageqa/qrels/full.qrels --collection_index ./data/wikipassageqa/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/wikipassageqa/collection/mapped_collection.tsv --mapper_path ./data/wikipassageqa/index/PID_Mapping.json

    # TREC CAsT 2019 Rocchio PRF
    python3 main.py --result_output ./result/trec_cast/2019/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_cast/2019/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json
    python3 main.py --result_output ./result/trec_cast/2019/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_cast/2019/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json
    python3 main.py --result_output ./result/trec_cast/2019/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_cast/2019/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json
    python3 main.py --result_output ./result/trec_cast/2019/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/trec_cast/2019/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/trec_cast/2019/query/full_queries.tsv --qrels_path ./data/trec_cast/2019/qrels/full.qrels --collection_index ./data/trec_cast/2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_cast/2019/collection/dedup_collection/mapped_collection.tsv --mapper_path ./data/trec_cast/2019/index/PID_Mapping.json

    # DL HARD Rocchio PRF
    python3 main.py --result_output ./result/dl_hard/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/dl_hard/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/dl_hard/ANCE_PRF_Runs/prf_retrieval.res --iteration_out ./result/dl_hard/ANCE_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/ANCE_FlatIP_collection.index --model ANCE --model_path ./ANCE_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/dl_hard/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/dl_hard/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --iterations 1 --prf "${prf}" --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv
    python3 main.py --result_output ./result/dl_hard/RepBERT_PRF_Runs/prf_retrieval.res --iteration_out ./result/dl_hard/RepBERT_PRF_Runs/prf_retrieval.res --prf_method rocchio --rocchio_beta "${i}" --has_alpha --iterations 1 --prf "${prf}" --query_tsv_file ./data/dl_hard/query/topics.tsv --qrels_path ./data/dl_hard/qrels/dl_hard-passage.qrels --collection_index ./data/trec_deep_2019/index/RepBERT_FlatIP_collection.index --model RepBERT --model_path ./RepBERT_Model --collection_file ./data/trec_deep_2019/collection/collection.tsv

  done
done
